//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Splusreport.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SPlusReportEntities : DbContext
    {
        public SPlusReportEntities()
            : base("name=SPlusReportEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DearlerFSMUpload> DearlerFSMUploads { get; set; }
        public virtual DbSet<SplusActivityUpload> SplusActivityUploads { get; set; }
        public virtual DbSet<StoreInfor> StoreInfors { get; set; }
    
        public virtual ObjectResult<SelectScoreDMX_Result> SelectScoreDMX()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectScoreDMX_Result>("SelectScoreDMX");
        }
    }
}
