//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Splusreport.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SPlusReportEntities : DbContext
    {
        public SPlusReportEntities()
            : base("name=SPlusReportEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DearlerFSMUpload> DearlerFSMUploads { get; set; }
        public virtual DbSet<SplusActivityUpload> SplusActivityUploads { get; set; }
        public virtual DbSet<StoreInfor> StoreInfors { get; set; }
        public virtual DbSet<Dayupdate> Dayupdates { get; set; }
    
        public virtual ObjectResult<SelectScoreDMX_Result> SelectScoreDMX()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectScoreDMX_Result>("SelectScoreDMX");
        }
    
        public virtual ObjectResult<SelectScoreMM_Result> SelectScoreMM()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectScoreMM_Result>("SelectScoreMM");
        }
    
        public virtual ObjectResult<SelectScoreNK_Result> SelectScoreNK()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectScoreNK_Result>("SelectScoreNK");
        }
    
        public virtual ObjectResult<SelectScorePICO_Result> SelectScorePICO()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectScorePICO_Result>("SelectScorePICO");
        }
    
        public virtual ObjectResult<SelectScoreVHC_Result> SelectScoreVHC()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectScoreVHC_Result>("SelectScoreVHC");
        }
    
        public virtual int ResetDealer(string dealer)
        {
            var dealerParameter = dealer != null ?
                new ObjectParameter("dealer", dealer) :
                new ObjectParameter("dealer", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ResetDealer", dealerParameter);
        }
    }
}
