//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Splusreport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DearlerFSMUpload
    {
        public int ID { get; set; }
        public string MNV { get; set; }
        public string SPlusCode { get; set; }
        public string Fullname { get; set; }
        public string Store { get; set; }
        public string Region { get; set; }
    }
}
